export const ACTION_TYPE = {
  SET_USER: "SET_USER",
  LOGOUT: "LOGOUT",
  SET_PRODUCT_DATA: "SET_PRODUCT_DATA",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  ADD_PRODUCT_TO_USER: "ADD_PRODUCT_TO_USER",
  DELETE_PRODUCT_IN_BASKET: "DELETE_PRODUCT_IN_BASKET",
  DELETE_BASKET: "DELETE_BASKET",
};
